Nodos Ejercicios
Ada-IT/ejercicios-frontend pull request #4
Opened 2020-10-08 18:36 UTC by eguisande

Ejercicios Nodos Ada

2020-10-08 18:37 UTC, pabloHoc commented on modulo-4/46-nodos.md
> +-- Creación nodo: Título
Poner numeral para titulo

```suggestion
## Creación nodo: Título
```

2020-10-08 18:37 UTC, pabloHoc requested changes
Fijate lo que te comente

2020-10-08 19:18 UTC, pabloHoc commented on modulo-4/46-nodos.md
> +En el menú anteriormente el li de contacto no era necesario para esta ocasión, por lo que deberemos eliminarlo.
Los de eliminar, más que modificar lo ya hecho, les daría un html y que lo eliminen de ahí, para que sea un ejercicio aparte y no sea confuso cómo hacerlo

2020-10-08 19:19 UTC, pabloHoc commented on modulo-4/46-nodos.md
> +Colocarle un color y una fuente a elección
Aclarar que es accediendo al DOM (no usando css)

2020-10-08 19:19 UTC, pabloHoc commented on modulo-4/46-nodos.md
> +Hacer que no tenga estilo de lista y que se visualice de manera horizontal
Esto lo sacaría porque ya es más CSS, para no mezclar los tantos

```suggestion
```

2020-10-08 19:20 UTC, pabloHoc commented on modulo-4/46-nodos.md
> +-- Crear una lista OL
Estaría bueno hacer lo mismo a partir de un array de strings

2020-10-08 19:26 UTC, pabloHoc commented on modulo-4/46-nodos.md
> +Crearemos un elemento div padre y le asignaremos un width y un height de 400px. Le insertaremos un elemento div hijo que ocupara el mayor alta y ancho posible teniendo un margen de 20px. Ambos deben
Aclarar que es sin usar html (podés hacerlo al principio de todo para no repetirlo). Lo estilos que no son dinámicos mejor no incluirlos porque se mezcla CSS y JS. Haría este ejercicio pero con una lista anidada por ejemplo.

2020-10-08 19:27 UTC, pabloHoc commented on modulo-4/46-nodos.md
> +
Esto también lo sacaría y buscaría hacer algo con estilo dinámicos

2020-10-08 19:31 UTC, pabloHoc commented on modulo-4/46-nodos.md
> +
Acá hay que detallarlo un poco más.
Definir que el contenedor y los estilos se hacen con HTML.
Que la grilla es un array que tienen que crearlo.
Que tienen que recorrer la grilla, etc. Como ejemplo:

```
Crear en html un div y ponerle la clase contenedor. Darle con css estilos para que tenga un alto y un ancho de 600px, que sea flexible y que tenga flex-wrap: wrap.
Crear en JS una variable llamada grilla que sea una matriz de 3x3.
Recorrer cada ítem de la grilla y por cada uno agregarle al contenedor un div con con la clase cuadrado.
En css, a la clase cuadrado darle un alto y un ancho de 180px y un margen de 10px.
```

2020-10-08 19:41 UTC, pabloHoc requested changes
@eguisande 

Genial Eze, van bien. Dos cositas:

En cuanto a los ejercicios:
- Darles un poco más de contexto a los ejercicios, qué tienen que crear y en dónde, separar estilos de CSS de los creados dinámicamente, y lo creado en HTML de lo creado con nodos
- No dar estilos con JS que se darían con CSS, para no llevar a malas prácticas, sólo estilos dinámicos
- Agregar un par de ejercicios más, que trabajen:
  - a partir de un array crear elementos
  - agregar listeners a elementos de dom creados dinámicamente (por ejemplo una todo list que al clickear el elemento se elimine, o una serie de botones donde cada uno consolee algo distinto, como el item de cada array)
   - una grilla que implique primero agregar un contenedor fila y después contenedor columna

Ejemplos:

```js
const frutas = ['manzana', 'pera', 'banana']
for (let fruta of frutas) {
  const button = document.createElement('button')
  button.innerText = "Clickeame"
  button.onclick = () => console.log(fruta)
}
```
```html
<div class="grilla">
  <div class="fila">
    <div class="columna"></div>
    <div class="columna"></div>
  </div>
  <div class="fila">
    <div class="columna"></div>
    <div class="columna"></div>
  </div>
</div>
```

Por otro lado, para darle un poco de estilos a markdown, podés usar caracteres especiales.

Para títulos, podes usar numerales

```
# h1
## h2
### h3
#### h4
```

Para ítems, un guión

- Item
  - Subitem
  - Subitem
- Item

Acá te dejo una guía
https://guides.github.com/features/mastering-markdown/

Estaría bueno poner el título del tema y los ejercicios como subtitulos
También ponerles un número a cada ejercicio, así lo pueden referenciar las chicas:

```
# Nodos
## Ejercicio 1 - Creación de nodo
## Ejercicio 2 - Creación de lista
```

2020-10-15 15:05 UTC, eguisande commented on modulo-4/46-nodos.md
> +-- Creación nodo: Título
Se modifico los # en el titulo.

2020-10-15 15:07 UTC, eguisande commented on modulo-4/46-nodos.md
> +En el menú anteriormente el li de contacto no era necesario para esta ocasión, por lo que deberemos eliminarlo.
Se le dio un listado de HTML accediendo desde el DOM para poder eliminar un elemento.

2020-10-15 15:07 UTC, eguisande commented on modulo-4/46-nodos.md
> +Colocarle un color y una fuente a elección
Se aclaro que deben acceder desde el DOM .

2020-10-15 15:08 UTC, eguisande commented on modulo-4/46-nodos.md
> +Hacer que no tenga estilo de lista y que se visualice de manera horizontal
Se elimino el ítem que implicaba Css.

2020-10-15 16:36 UTC, eguisande commented on modulo-4/46-nodos.md
> +Crearemos un elemento div padre y le asignaremos un width y un height de 400px. Le insertaremos un elemento div hijo que ocupara el mayor alta y ancho posible teniendo un margen de 20px. Ambos deben
Se creo un ejercicio en cual deben replicar una  lista anidada accediendo desde Nodos

2020-10-15 17:28 UTC, eguisande commented on modulo-4/46-nodos.md
> +-- Crear una lista OL
Ejercicio modificado

2020-10-15 17:29 UTC, eguisande commented on modulo-4/46-nodos.md
> +
Se modifico con una lista anidada, Mostrando un ejemplo y deberán replicarla mediante Nodes

2020-10-15 18:37 UTC, eguisande commented on modulo-4/46-nodos.md
> +
Se corrigió la descripción del ejercicio.

2020-10-22 14:29 UTC, pabloHoc commented
Eze, por ahora mergeo y le sumo algunas cosas porque ya estamos medio justo con los tiempos, después si querés echale una ojeada. Gracias!

2020-10-22 14:29 UTC, merged