Callbacks
Ada-IT/ejercicios-frontend pull request #5
Opened 2020-10-12 18:05 UTC by eguisande

Ejercicios Callbacks

2020-10-13 14:50 UTC, pabloHoc commented on modulo-4/47-callbacks.md
> +
Eze, la redactaría un poco distinto para que se entienda mejor lo que se requiere, por ejemplo:

Crear una función que reciba como argumento un `callback`. La función debe pedir el nombre de un usuario mediante un `prompt`. Una vez ingresado, debe ejecutar el `callback`. Por ejemplo:

```js
const mostrarMensajeConfirmacion = () => alert('Usuario creado!') // callback
 
crearUsuario(mostrarMensajeConfirmacion)

// Por favor ingrese un usuario:
// Ada Lovelace
// Usuario creado!
```

2020-10-13 14:59 UTC, pabloHoc commented on modulo-4/47-callbacks.md
> +Y aquí validaremos si el nombre de usuario contiene o no espacios en el mismo. De ser así le mostraremos un mensaje de error, caso contrario el mensaje que anteriormente habíamos definido.
También definirlo un poco más claro y explícito. **Siempre en vez de mejorar algo ya hecho, hacer algo nuevo, para evitar confusión, no importa que sea repetitivo.**

Aclarar que el callback tiene que recibir un parámetro. Aclarar que la validación se tiene que dar en el callback. Por ejemplo:

Crear una función que reciba como argumento un `callback` como función validadora de nombres. El `callback` debe tomar un `string` como parámetro y devolver true o false si el parámetro pasa la validación. Ejemplos de validación:
- Que el string no tenga espacios
- Que el string tenga más de un caractere
- Que el string no tenga números
El `callback` solo tiene que validar una de estas cosas.

La función debe pedir el nombre de un usuario mediante un prompt. Una vez ingresado, debe ejecutar el `callback`, pasándole como parámetro el usuario ingresado. Si el `callback` devuelve `true`, mostrar un mensaje de confirmación, si devuelve `false`, mostrar uno de error. Por ejemplo:

```js
crearUsuario(validarLongitud)

// Por favor ingrese un usuario:
// L
// El usuario ingresado no tiene el formato correcto
```

2020-10-13 14:59 UTC, pabloHoc commented on modulo-4/47-callbacks.md
> +
Acá no vieron objetos

2020-10-13 14:59 UTC, pabloHoc commented on modulo-4/47-callbacks.md
> +Realizar una función que le permita al usuario ingresar un país mediante un prompt y enviarlo como parámetro al callback (Utilizar el array del punto anterior) y mostrar un popup para saber si el paí
El popup es un alert? O lo tienen que maquetar?

2020-10-13 15:00 UTC, pabloHoc commented on modulo-4/47-callbacks.md
> +Crearemos un campo texto con un valor "cargando..." y al cabo de 5 segundos ese texto debe actualizarse a "tarea realizada".
Hacerlo con una función

2020-10-13 15:01 UTC, pabloHoc commented on modulo-4/47-callbacks.md
> +Crearemos un botón que dispare una función con un timeout de 10 segundos, cuando se ejecute debe grisear el botón para no permitirle al usuario realizar esta acción, una vez transcurridos los 10 segu
Cómo se grisea? Deshabilitándolo? Cambiándole estilos?

2020-10-13 15:32 UTC, pabloHoc commented on modulo-4/47-callbacks.md
> +Debemos mostrarlo en el centro de la pantalla con un tamaño de Fuente de al menos 48px.
Genial este, también haría uno similar para crear el efecto máquina de escribir (ir concatenando y escribiendo de a poco)

2020-10-13 15:33 UTC, pabloHoc commented on modulo-4/47-callbacks.md
> +Crear una función interval que cada 100ms se eleje de su margen izquierdo 10px. Siempre y cuando no supere un total de 700px de dicho margen.
Más que margen usaría position absolute

2020-10-13 19:18 UTC, pabloHoc requested changes
Eze, dos cosas: Si podés de este PR eliminá el archivo de nodos, así no se mezcla cuando hagamos merge.

Después te dejé unos comentarios en relación a callbacks. Mayormente la idea es redactarlos dando un poco más de detalles y contexto, para ser lo más claro posible y evitar posibles confusiones. También tratá de formatearlo como te comenté en el PR de nodos, así ya queda listo.

Me gustó el de validación y el de ejecutar algo después de una operación, si podés sumar 3 o 4 de esa índole genial.

Gracias!

2020-10-13 19:25 UTC, pabloHoc commented
Por otro lado, los de animaciones no me terminan de convencer, porque se pueden hacer con CSS y es medio difícil aplicarlos en la vida real. De última darle más énfasis a alguno otro de callback y no tanto de setTimeout.

2020-10-19 13:46 UTC, eguisande commented on modulo-4/47-callbacks.md
> +
Se modifico la redacción.

2020-10-19 13:47 UTC, eguisande commented on modulo-4/47-callbacks.md
> +Y aquí validaremos si el nombre de usuario contiene o no espacios en el mismo. De ser así le mostraremos un mensaje de error, caso contrario el mensaje que anteriormente habíamos definido.
Se modifico la redacción

2020-10-19 14:00 UTC, eguisande commented on modulo-4/47-callbacks.md
> +Realizar una función que le permita al usuario ingresar un país mediante un prompt y enviarlo como parámetro al callback (Utilizar el array del punto anterior) y mostrar un popup para saber si el paí
Se especifico que el callback debe devolver un alerta

2020-10-19 14:08 UTC, eguisande commented on modulo-4/47-callbacks.md
> +
Se modifico el array de objetos a solo strings

2020-10-19 14:19 UTC, eguisande commented on modulo-4/47-callbacks.md
> +Crearemos un campo texto con un valor "cargando..." y al cabo de 5 segundos ese texto debe actualizarse a "tarea realizada".
Se agrego la especificación de hacerlo con una función.

2020-10-19 14:37 UTC, eguisande commented on modulo-4/47-callbacks.md
> +Crearemos un botón que dispare una función con un timeout de 10 segundos, cuando se ejecute debe grisear el botón para no permitirle al usuario realizar esta acción, una vez transcurridos los 10 segu
Se modifico y especifico la deshabilitación del botón.

2020-10-20 15:19 UTC, eguisande commented on modulo-4/47-callbacks.md
> +Crear una función interval que cada 100ms se eleje de su margen izquierdo 10px. Siempre y cuando no supere un total de 700px de dicho margen.
Se elimino este ejercicio y se adicionan mas ejercicios de callbacks

2020-10-22 14:29 UTC, pabloHoc commented
Eze, por ahora mergeo y le sumo algunas cosas porque ya estamos medio justo con los tiempos, después si querés echale una ojeada. Gracias!

2020-10-22 14:30 UTC, merged